#!/bin/bash

THERE_IS_NO_CONFIGURATION_FILE='There is no configuration file.'

print_message () {
  printf "\033[1;%sm%s\033[0m\n" "$1" "$2"
}

if [ ! -f ./pyproject.toml ] || [ ! -f ./.isort.cfg ] || [ ! -f ./mypy.ini ] || [ ! -f ./.flake8 ]
then
  print_message "31" "$THERE_IS_NO_CONFIGURATION_FILE"
else
  print_message "33" "Isort:"
  isort . && echo -e \\n
  print_message "37" "Black:"
  black . && echo -e \\n
  print_message "34" "Mypy:"
  mypy . && echo -e \\n
  print_message "35" "Flake8:"
  flake8 .
#  flake8 . || echo 'asdf'
fi
